install: install-requirements install-chatgpt

install-requirements:
	pip install -r requirements.txt

install-chatgpt:
	brew tap lencx/chatgpt https://github.com/lencx/ChatGPT.git
	brew install --cask chatgpt --no-quarantine